import Head from 'next/head'
import App from '../components/0app'

export default function Main() {
  return (
    <>
      <Head>
        <title>CONWAY_HASH$</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <App></App>
    </>
  )
}
